apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert --file ..\docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-kompose
  name: frontend-kompose
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-kompose
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\system32\kompose.exe convert --file ..\docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend-kompose
    spec:
      hostAliases:
       - ip: "10.43.242.240" # Make sure this is the server service's ip address in the cluster ,the nginx deployment from frontend is requesting for http://server:5000
         hostnames:
         - server
      containers:
        - image: gitlab.ldv.ei.tum.de:5005/ami2022/group04:ami_frontend
          imagePullPolicy: Always
          name: frontend-kompose
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

status: {}
