apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert --file ..\docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: server-kompose
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server-kompose
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\system32\kompose.exe convert --file ..\docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: server-kompose
    spec:
      containers:
        - image: gitlab.ldv.ei.tum.de:5005/ami2022/group04:ami_server
          name: server
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - name: smb
              mountPath: "/mnt/smb"
              readOnly: false
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-smb-group04
status: {}
