apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert --file ..\docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-kompose
  name: frontend-kompose-service
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 80
      nodePort: 30401

  selector:
    io.kompose.service: frontend-kompose
