apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-smb-group04
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: group04pv-qweasd
    volumeAttributes:
      source: "//10.195.8.70/group04"
    nodeStageSecretRef:
      name: smbcreds-group04
      namespace: group04
