kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-group04
  namespace: group04
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: smb